### ISSUE TITLE
can't understand this expression player's top position

### ISSUE THREAD

**Issue by pawelkuwa** [FunnyGuilds/FunnySkAddon#20]
skript nie widzi wyrażenia "player's top position"
wersja silnika: This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
wersja funnyguilds: 4.9.7 Tribute-1730267
wersja funnyskaddon: 2.2.1
java: 1.8.0_301

logi z konsoli podczas stratu: https://pastebin.com/hPBTW950

**Comment by P3ridot** [comment]
Użyj wyrażenia `player position`
