### ISSUE TITLE
on break issue

### ISSUE THREAD

**Issue by pawelkuwa** [FunnyGuilds/FunnySkAddon#24]
https://github.com/SkriptLang/Skript/issues/4482

**Comment by P3ridot** [comment]
Użyj [FunnySkAddon 2.2.10-Beta](https://github.com/FunnyGuilds/FunnySkAddon/releases/tag/2.2.10-Beta) oraz [FunnyGuilds 4.10.0 (Nightyl)](https://ci.insertt.dev/job/FunnyGuilds/) tam zostało to naprawione
