### ISSUE TITLE
Uncomputable expressions in events

### ISSUE THREAD

**Issue by pawelkuwa** [FunnyGuilds/FunnySkAddon#28]
![image](https://user-images.githubusercontent.com/83598982/149619673-aa86afec-51db-4de9-aad2-f683f17e5f9b.png)
![image](https://user-images.githubusercontent.com/83598982/149619676-215ff507-2edb-4bfd-8cd3-975364f4fece.png)

**Comment by P3ridot** [comment]
Zostało to naprawione w [FunnySkAddon 2.2.11](https://github.com/FunnyGuilds/FunnySkAddon/releases/tag/2.2.11-Beta)
