### ISSUE TITLE
Negated conditions not working properly

### ISSUE THREAD

**Issue by pawelkuwa** [FunnyGuilds/FunnySkAddon#30]
![image](https://user-images.githubusercontent.com/83598982/150638607-1f7c3d83-288c-4ea4-b3fd-af7c2e6175b3.png)
gdy wykonuje kod w taki sposób, i gdy nie mam gildii, wiadomość wysyła się "nie"

![image](https://user-images.githubusercontent.com/83598982/150638646-a86ca7b7-a9ac-451e-b0c0-a6273e1030ce.png)
a gdy wykonuje taki kod, i gdy nie mam gildii, wiadomość wysyła się "test"

**Comment by P3ridot** [comment]
Naprawione w [2.12.2-Beta](https://github.com/FunnyGuilds/FunnySkAddon/releases/tag/2.2.12-Beta)
