### ISSUE TITLE
Invalid value of isSingle method

### ISSUE THREAD

**Issue by pawelkuwa** [FunnyGuilds/FunnySkAddon#44]
![image](https://user-images.githubusercontent.com/83598982/152703279-9629d60e-6acd-4da4-888c-6e7a52901bd9.png)
![image](https://user-images.githubusercontent.com/83598982/152703283-0005c302-6d77-41c2-8bfd-2d2f16d319bc.png)
![image](https://user-images.githubusercontent.com/83598982/152703300-19c70810-ac57-4d35-9189-688abf32be91.png)

**Comment by P3ridot** [comment]
Naprawione w [2.2.19-Beta](https://github.com/FunnyGuilds/FunnySkAddon/releases/tag/2.2.19-Beta)
