### ISSUE TITLE
Problem z panda.std.Option

### ISSUE THREAD

**Issue by fejks1** [FunnyGuilds/FunnySkAddon#57]
Mam problem

Skript 2.6.1
Wersja MC 1.17.1
FunnySkAddon v2.2.21-Beta

Błąd: https://pastebin.com/UyvFx41S

**Comment by fejks1** [comment]
Z DOŁU DZIENKUJE

**Comment by Kamilkime** [comment]
Jest już nowsza wersja FG i FunnySkAddon - najlepiej ich użyj i zobacz czy błąd nadal występuje

**Comment by P3ridot** [comment]
Na pewno zaktualizuj FunnyGuilds i FunnySkAddon i podaj więcej informacji - kiedy błąd występuje, jaka część dokładnie nie działa itp.
